export const typeColors: Record<string, string> = {
  normal: "bg-gray-300 text-gray-800",
  fire: "bg-red-400 text-white",
  water: "bg-blue-400 text-white",
  electric: "bg-yellow-300 text-black",
  grass: "bg-green-400 text-white",
  ice: "bg-blue-200 text-black",
  fighting: "bg-red-700 text-white",
  poison: "bg-purple-500 text-white",
  ground: "bg-yellow-600 text-white",
  flying: "bg-indigo-300 text-black",
  psychic: "bg-pink-500 text-white",
  bug: "bg-green-600 text-white",
  rock: "bg-gray-600 text-white",
  ghost: "bg-indigo-700 text-white",
  dragon: "bg-purple-800 text-white",
  dark: "bg-gray-800 text-white",
  steel: "bg-gray-400 text-black",
  fairy: "bg-pink-300 text-black",
};

export const pokemonTypes = [
  "Normal",
  "Fire",
  "Water",
  "Electric",
  "Grass",
  "Ice",
  "Fighting",
  "Poison",
  "Ground",
  "Flying",
  "Psychic",
  "Bug",
  "Rock",
  "Ghost",
  "Dragon",
  "Dark",
  "Steel",
  "Fairy",
];
